services:
  php:
    build: .
    ports:
      - "8888:80"
    volumes:
      - .:/var/www/html
    environment:
      - DOCKER_ENV=true
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: academic
      MYSQL_USER: sikauser
      MYSQL_PASSWORD: sikapass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./academic.sql:/docker-entrypoint-initdb.d/academic.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8889:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data:
